<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSurveyAnswersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user_survey_answers')->insert([

            // User Survey 1
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 1,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 2,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 3,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 4,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 5,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 1,
                'survey_question_option_id' => 6,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 1,
                'survey_question_id' => 2,
                'survey_question_option_id' => null,
                'value_integer' => 670,
                'value_boolean' => null,
            ],

            // User Survey 2
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 2,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 4200,
                'value_boolean' => null,
            ],

            // User Survey 3
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 3,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 400,
                'value_boolean' => null,
            ],

            // User Survey 4
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 1,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 2,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 3,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 4,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 5,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 1,
                'survey_question_option_id' => 6,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 4,
                'survey_question_id' => 2,
                'survey_question_option_id' => null,
                'value_integer' => 1400,
                'value_boolean' => null,
            ],

            // User Survey 5
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 1,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 2,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 3,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 4,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 5,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 1,
                'survey_question_option_id' => 6,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 5,
                'survey_question_id' => 2,
                'survey_question_option_id' => null,
                'value_integer' => 400,
                'value_boolean' => null,
            ],

            // User Survey 6
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 1,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 2,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 3,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 4,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 5,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 1,
                'survey_question_option_id' => 6,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 6,
                'survey_question_id' => 2,
                'survey_question_option_id' => null,
                'value_integer' => 470,
                'value_boolean' => null,
            ],

            // User Survey 7
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 7,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 5200,
                'value_boolean' => null,
            ],

            // User Survey 8
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 1,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 2,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 3,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 4,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 5,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 1,
                'survey_question_option_id' => 6,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 8,
                'survey_question_id' => 2,
                'survey_question_option_id' => null,
                'value_integer' => 546,
                'value_boolean' => null,
            ],

            // User Survey 9
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 13,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 14,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 15,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 16,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 17,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 5,
                'survey_question_option_id' => 18,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 9,
                'survey_question_id' => 6,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 10
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 10,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 11
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 13,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 14,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 15,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 16,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 17,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 5,
                'survey_question_option_id' => 18,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 11,
                'survey_question_id' => 6,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 12
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 13,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 14,
                'value_integer' => null,
                'value_boolean' => false,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 15,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 16,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 17,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 5,
                'survey_question_option_id' => 18,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 12,
                'survey_question_id' => 6,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 13
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 13,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 14,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 15,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 16,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 17,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 5,
                'survey_question_option_id' => 18,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 13,
                'survey_question_id' => 6,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 14
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 14,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

            // User Survey 15
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 7,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 8,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 9,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 10,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 11,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 3,
                'survey_question_option_id' => 12,
                'value_integer' => null,
                'value_boolean' => true,
            ],
            [
                'user_survey_id' => 15,
                'survey_question_id' => 4,
                'survey_question_option_id' => null,
                'value_integer' => 6200,
                'value_boolean' => null,
            ],

        ]);
    }
}
